# Generated by Django 4.2.11 on 2025-12-27 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("bio", models.TextField(blank=True)),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="artists/"),
                ),
                (
                    "cover_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="artists/covers/"
                    ),
                ),
                ("verified", models.BooleanField(default=False)),
                ("monthly_listeners", models.PositiveIntegerField(default=0)),
                ("website", models.URLField(blank=True)),
                ("spotify_url", models.URLField(blank=True)),
                ("instagram", models.CharField(blank=True, max_length=100)),
                ("twitter", models.CharField(blank=True, max_length=100)),
                ("country", models.CharField(blank=True, max_length=2)),
            ],
            options={
                "db_table": "artists",
                "ordering": ["-monthly_listeners", "name"],
            },
        ),
        migrations.CreateModel(
            name="ArtistMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("role", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="artist_members/"
                    ),
                ),
                ("join_date", models.DateField(blank=True, null=True)),
                ("leave_date", models.DateField(blank=True, null=True)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="artists.artist",
                    ),
                ),
            ],
            options={
                "db_table": "artist_members",
            },
        ),
    ]
