# Generated by Django 4.2.11 on 2025-12-26 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("music", "0001_initial"),
        ("artists", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="artist",
            name="genres",
            field=models.ManyToManyField(
                blank=True, related_name="artists", to="music.genre"
            ),
        ),
        migrations.AddIndex(
            model_name="artist",
            index=models.Index(fields=["name"], name="artists_name_b2ca99_idx"),
        ),
        migrations.AddIndex(
            model_name="artist",
            index=models.Index(fields=["slug"], name="artists_slug_91e4ea_idx"),
        ),
    ]
