# Generated by Django 4.2.11 on 2025-12-27 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("artists", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Album",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                (
                    "album_type",
                    models.CharField(
                        choices=[
                            ("album", "Album"),
                            ("single", "Single"),
                            ("ep", "EP"),
                            ("compilation", "Compilation"),
                        ],
                        default="album",
                        max_length=20,
                    ),
                ),
                ("release_date", models.DateField()),
                ("cover_image", models.ImageField(upload_to="albums/")),
                ("description", models.TextField(blank=True)),
                ("label", models.CharField(blank=True, max_length=255)),
                ("total_duration", models.PositiveIntegerField(default=0)),
                ("total_tracks", models.PositiveIntegerField(default=0)),
                ("play_count", models.PositiveIntegerField(default=0)),
                ("is_explicit", models.BooleanField(default=False)),
                ("copyright", models.CharField(blank=True, max_length=255)),
                ("upc", models.CharField(blank=True, max_length=20)),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="albums",
                        to="artists.artist",
                    ),
                ),
            ],
            options={
                "db_table": "albums",
                "ordering": ["-release_date"],
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="subgenres",
                        to="music.genre",
                    ),
                ),
            ],
            options={
                "db_table": "genres",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Song",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(db_index=True, max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("audio_file", models.FileField(upload_to="songs/")),
                ("audio_url", models.URLField(blank=True)),
                ("duration", models.PositiveIntegerField()),
                ("track_number", models.PositiveIntegerField(default=1)),
                ("disc_number", models.PositiveIntegerField(default=1)),
                ("isrc", models.CharField(blank=True, max_length=12)),
                ("lyrics", models.TextField(blank=True)),
                ("is_explicit", models.BooleanField(default=False)),
                ("mood", models.CharField(blank=True, max_length=50)),
                ("language", models.CharField(blank=True, max_length=10)),
                ("play_count", models.PositiveIntegerField(default=0)),
                ("like_count", models.PositiveIntegerField(default=0)),
                ("tempo", models.FloatField(blank=True, null=True)),
                ("key", models.CharField(blank=True, max_length=5)),
                ("energy", models.FloatField(blank=True, null=True)),
                ("danceability", models.FloatField(blank=True, null=True)),
                ("valence", models.FloatField(blank=True, null=True)),
                (
                    "album",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="music.album",
                    ),
                ),
                (
                    "artist",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="songs",
                        to="artists.artist",
                    ),
                ),
                (
                    "featured_artists",
                    models.ManyToManyField(
                        blank=True, related_name="featured_songs", to="artists.artist"
                    ),
                ),
                (
                    "genre",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="songs",
                        to="music.genre",
                    ),
                ),
            ],
            options={
                "db_table": "songs",
                "ordering": ["album", "disc_number", "track_number"],
                "indexes": [
                    models.Index(fields=["title"], name="songs_title_82952e_idx"),
                    models.Index(
                        fields=["artist", "title"], name="songs_artist__bd4820_idx"
                    ),
                    models.Index(
                        fields=["play_count"], name="songs_play_co_5fb479_idx"
                    ),
                ],
                "unique_together": {("album", "slug")},
            },
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(fields=["title"], name="albums_title_063196_idx"),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["release_date"], name="albums_release_27939f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["artist", "release_date"], name="albums_artist__35de25_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="album",
            unique_together={("artist", "slug")},
        ),
    ]
