# Generated by Django 4.2.11 on 2025-12-27 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("artists", "0002_initial"),
        ("music", "0001_initial"),
        ("interactions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="savedalbum",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="saved_albums",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="music.album",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="song",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="music.song",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="listeninghistory",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="plays",
                to="music.song",
            ),
        ),
        migrations.AddField(
            model_name="listeninghistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="listening_history",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="likedsong",
            name="song",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="likes",
                to="music.song",
            ),
        ),
        migrations.AddField(
            model_name="likedsong",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="liked_songs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="followedartist",
            name="artist",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to="artists.artist",
            ),
        ),
        migrations.AddField(
            model_name="followedartist",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followed_artists",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="savedalbum",
            unique_together={("user", "album")},
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["album", "-created_at"], name="reviews_album_i_29c42d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["song", "-created_at"], name="reviews_song_id_3e7ec1_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listeninghistory",
            index=models.Index(
                fields=["user", "-played_at"], name="listening_h_user_id_481e20_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="listeninghistory",
            index=models.Index(
                fields=["song", "-played_at"], name="listening_h_song_id_644e23_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="likedsong",
            index=models.Index(
                fields=["user", "-created_at"], name="liked_songs_user_id_d37a22_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="likedsong",
            unique_together={("user", "song")},
        ),
        migrations.AlterUniqueTogether(
            name="followedartist",
            unique_together={("user", "artist")},
        ),
    ]
