# Generated by Django 4.2.11 on 2025-12-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("music", "0001_initial"),
        ("artists", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Radio",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "radios",
            },
        ),
        migrations.CreateModel(
            name="UserTaste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("energy_preference", models.FloatField(default=0.5)),
                ("danceability_preference", models.FloatField(default=0.5)),
                ("valence_preference", models.FloatField(default=0.5)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "favorite_genres",
                    models.ManyToManyField(related_name="fans", to="music.genre"),
                ),
                (
                    "top_artists",
                    models.ManyToManyField(
                        related_name="top_listeners", to="artists.artist"
                    ),
                ),
            ],
            options={
                "db_table": "user_taste",
            },
        ),
    ]
