# Generated by Django 4.2.11 on 2025-12-27 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("artists", "0002_initial"),
        ("music", "0001_initial"),
        ("recommendations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertaste",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="taste",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="radio",
            name="seed_artist",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="artists.artist",
            ),
        ),
        migrations.AddField(
            model_name="radio",
            name="seed_genre",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="music.genre",
            ),
        ),
        migrations.AddField(
            model_name="radio",
            name="seed_song",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="music.song",
            ),
        ),
        migrations.AddField(
            model_name="radio",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="radios",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
