# Generated by Django 4.2.11 on 2025-12-27 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="playlists/"),
                ),
                ("is_public", models.BooleanField(default=True)),
                ("is_collaborative", models.BooleanField(default=False)),
                ("is_editorial", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
