# Generated by Django 4.2.11 on 2026-01-08 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("playlists", "0003_playlistsong_playlistfollower"),
    ]

    operations = [
        migrations.AddField(
            model_name="playlist",
            name="follower_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="playlist",
            name="total_duration",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
